#!/bin/bash

# generate-decision-log.sh
# Auto-generates DECISION_LOG.md from session document frontmatter
# Extracts decisions that have:
#   1. Related issues (indicates a decision tied to a problem)
#   2. Related commits (implementation of a decision)
#   3. Future scope (ideas worth tracking)

set -e

DOCS_DIR="docs/sessions"
DECISION_LOG="$DOCS_DIR/DECISION_LOG.md"

echo "Generating decision log from session frontmatter..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Create decision log
cat > "$DECISION_LOG" << 'EOFHEADER'
---
date: 2025-12-09
topic: documentation
status: active
related_issues: [#30]
---

# Decision Log

**Auto-generated from session document frontmatter**  
**Last updated**: [AUTO]

Architectural and technical decisions made during Forge Terminal development.
Each decision is linked to the session documentation where it was explored and discussed.

---

## 📖 How to Use This Log

- **Find a decision**: Search below or use `./scripts/find-decision.sh`
- **Understand context**: Click session link for full exploration
- **Check status**: See if ACTIVE, IMPLEMENTED, or ARCHIVED
- **Related artifacts**: Links to GitHub issues and commits

---

## Key Decisions by Topic

EOFHEADER

# Extract unique topics from session docs with decisions
TOPICS=$(find "$DOCS_DIR" -maxdepth 2 -name "*.md" -type f ! -path "*/archive/*" -exec grep "^related_issues:" {} + 2>/dev/null | wc -l)

if [[ $TOPICS -gt 0 ]]; then
  # Find all docs with related_issues or related_commits
  find "$DOCS_DIR" -maxdepth 2 -name "*.md" -type f ! -path "*/archive/*" | while read -r file; do
    issues=$(grep "^related_issues:" "$file" 2>/dev/null | head -1)
    commits=$(grep "^related_commits:" "$file" 2>/dev/null | head -1)
    
    # Skip if no issues or commits (not a decision)
    if [[ -z "$issues" ]] && [[ -z "$commits" ]]; then
      continue
    fi
    
    # Extract fields
    date=$(grep "^date:" "$file" 2>/dev/null | head -1 | awk '{print $2}' | tr -d "'\"")
    topic=$(grep "^topic:" "$file" 2>/dev/null | head -1 | awk '{print $2}' | tr -d "'\"")
    title=$(grep "^#" "$file" 2>/dev/null | head -1 | sed 's/^# //' | tr -d '`')
    issues_text=$(echo "$issues" | sed 's/related_issues: //' | tr -d '[]')
    commits_text=$(echo "$commits" | sed 's/related_commits: //' | tr -d '[]')
    
    # Format decision entry
    relpath=$(echo "$file" | sed "s|$DOCS_DIR/||")
    
    {
      echo "### $title"
      echo ""
      if [[ ! -z "$date" ]] && [[ ! "$date" =~ ^1970 ]]; then
        echo "- **Date**: $date"
      fi
      echo "- **Topic**: $topic"
      echo "- **Session**: [$relpath]($relpath)"
      
      if [[ ! -z "$issues_text" ]]; then
        echo "- **Issues**: $issues_text"
      fi
      
      if [[ ! -z "$commits_text" ]]; then
        echo "- **Commits**: $commits_text"
      fi
      
      echo "- **Status**: 🟢 IMPLEMENTED"
      echo ""
    } >> "$DECISION_LOG"
  done
fi

# Add footer
cat >> "$DECISION_LOG" << 'EOFFOOTER'

---

## How to Add Decisions

1. Create session doc with frontmatter:
   ```yaml
   ---
   date: YYYY-MM-DD
   topic: feature-name
   status: active
   related_issues: [#22, #25]  # ← Links to GitHub issues
   related_commits: [abc123]    # ← Links to implementation
   ---
   ```

2. Run to update log:
   ```bash
   ./scripts/generate-decision-log.sh
   ```

3. Decision appears in log automatically with:
   - Title from markdown heading
   - Session link
   - Related issues and commits
   - Date and topic

---

## Searching Decisions

Use the find-decision.sh helper:
```bash
./scripts/find-decision.sh "model selector"
./scripts/find-decision.sh "assistant"
./scripts/find-decision.sh "logging"
```

Or search manually:
```bash
grep -i "decision title" docs/sessions/DECISION_LOG.md
```

---

**Auto-generated by**: `./scripts/generate-decision-log.sh`
EOFFOOTER

echo "✓ Generated DECISION_LOG.md"
echo "  • $(wc -l < "$DECISION_LOG") lines"
echo "  • Extracted decisions from session frontmatter"
echo ""
